# JWT Configuration (Stateless)
jwt.secret=your-secret-key-min-256-bits-change-this-in-production
jwt.expiration=3600000

# Spring Security
spring.security.filter.dispatcher-types=REQUEST,FORWARD,ERROR

# Exemplo de outras configurações
spring.application.name=LicitAi
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration